### ISSUE TITLE
How to avoid creating an empty config.json when dont need any setting

### ISSUE THREAD

**Issue by jacargentina** [pouchdb/express-pouchdb#160]
I'm using the module, and constantly having to remove the empty created `config.json` file, cause i dont need/want any special setting. There is some way on current code to avoid that?

**Comment by marten-de-vries** [comment]
``config.json`` is still very new and until some of the current PRs are merged, the only thing you can do is changing the location of it (e.g. to /tmp/ or similar). To do that, call express-pouchdb like this:
```javascript
require('express-pouchdb')(PouchDB, {configPath: '/tmp/config.json'})
```

As soon as #155 is merged + released, you could instead disable the part of express-pouchdb that handles configuration completely.

If both aren't good enough for your use case, e.g. because you need a part of express-pouchdb that uses a config option but the default is ok for you, then report back with your use case and we can look further into the issue from that.

``log.txt`` will likely give you the same problem, in that case you can just set the log file to /dev/null and/or set the log level to 'none'. (Or use #155 again as soon as it's merged.)

**Comment by nolanlawson** [comment]
`configPath` doesn't seem to be documented in the README. Could you add it?

**Comment by marten-de-vries** [comment]
@nolanlawson It's in the start I made in #155, as soon as stuff is merged (so I know *what* needs to be documented) that is the next thing on my todo list for express-pouchdb.

**Comment by marten-de-vries** [comment]
Closing. No config file is created unless it's used.
