### ISSUE TITLE
express-pouchdb started failing pouchdb tests today

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/express-pouchdb#203]
Looks like the pouchdb-server tests are consistently failing in Travis as of today (see https://github.com/pouchdb/pouchdb/pull/3749#issuecomment-96277434). I'm guessing it's because of the `pouchdb-security` update @marten-de-vries? Else I'm not sure.

The error we're seeing is:

```
  1) test.design_docs.js-http "before each" hook:
     Uncaught Error: ETIMEDOUT
      at onError (/home/travis/build/pouchdb/pouchdb/lib/deps/ajax.js:66:18)
      at Request._callback (/home/travis/build/pouchdb/pouchdb/lib/deps/ajax.js:108:14)
      at self.callback (/home/travis/build/pouchdb/pouchdb/node_modules/request/request.js:123:22)
      at Request.emit (events.js:95:17)
      at null._onTimeout (/home/travis/build/pouchdb/pouchdb/node_modules/request/request.js:590:12)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by marten-de-vries** [comment]
Looking into this now. ``pouchdb-wrappers`` & ``pouchdb-security-db`` also got an upgrade, so that means the fail of #204 is not yet conclusive.

**Comment by marten-de-vries** [comment]
So turns out the culprit is actually my hack to work around https://github.com/pouchdb/pouchdb/pull/3434 being wrong, this was also the first ``pouchdb-wrappers`` release to include that.

I'm going to revert that change for now, because otherwise it's going to be an even uglier hack. That means we're back to seeing (in this case false) deprecation warnings in the log.

The long term solution is instead to actually put some work into deprecating ``PouchDB.destroy()`` properly. I.e., in such a way that you can actually write something like the following without making ``db.destroy()`` crash:

```javascript
PouchDB.destroy = function (name, opts, cb) {
  var args = parseArgs(name, opts, cb);
  var db = new PouchDB(args.name, args.opts);
  var promise = db.destroy(args.opts);
  nodify(promise, args.callback);
  return promise;
}
```

If ``PouchDB.destroy()`` is ever to be removed, it needs to happen regardless. Better to do it quickly, I guess.

**Comment by marten-de-vries** [comment]
https://travis-ci.org/pouchdb/pouchdb/jobs/60034164 just passed, which is confirmation from Travis that reverting the .destroy() hack in ``pouchdb-wrappers`` indeed is a workaround.
