### ISSUE TITLE
allDocs row count and info doc_count are set wrong when using Express-PouchDB

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/express-pouchdb#267]
About 80% of the time when I run the code [here](https://gist.github.com/yaronyg/2d0c7d59e97c9a107027) in node.js I will get back the wrong document count both on doc_count from info as well as from total_rows on allDocs.

All the data is stored correctly and it is contained in the rows object on allDocs. It's the count that is wrong.

The way I cause this error is that I do a bunch of writes directly to PouchDB("foo") and then I run Express-PouchDB in the same instance and do a bunch of writes to PouchDB("http://127.0.0.1:5984/foo"). In other words, I'm writing to the same underlying DB (from inside of the same Node.js instance so there are no process boundary issues) but in some cases I submit the write directly and in others I go through Express-PouchDB.

Note that when I write directly to local objects (e.g. write to two different instances of PouchDB("foo") running in the same Node.js process) I haven't been able to repo this bug.

**Comment by nolanlawson** [comment]
Yes, this is something we currently don't support - accessing a LevelDB database *both* from express-pouchdb and from a totally separate PouchDB in a separate Node VM.

The reason you're seeing different counts is because we maintain an in-memory cache of that count (for performance), so if you access it from separate VMs then that won't be shared.

The fix is to do all your PouchDB stuff inside of a single Node VM, which can be accomplished in express-pouchdb because you pass in the `PouchDB` object yourself.

**Comment by nolanlawson** [comment]
It is worth considering, though, that this could cause issues in other environments as well - e.g. using the same PouchDB from two different tabs.

**Comment by yaronyg** [comment]
@nolanlawson To be super duper clear - All access (both local and to Express) are in the SAME Node VM.

If you look at the source code I linked to above (see [here](https://gist.github.com/yaronyg/2d0c7d59e97c9a107027)) you will see that I start a single node VM instance and from inside of that single Node VM instance I use the PouchDB instance created [here](https://gist.github.com/yaronyg/2d0c7d59e97c9a107027#file-test-js-L3)  both to create the Express Instance (see [here](https://gist.github.com/yaronyg/2d0c7d59e97c9a107027#file-test-js-L10)) and the local PouchDB instances (see [here](https://gist.github.com/yaronyg/2d0c7d59e97c9a107027#file-test-js-L69-L70)). And all requests, all tests, everything, are doing completely inside of that Node VM instance.

So if I understand your comment you are saying that the caching logic is common to all PouchDB instances created in the same Node VM. Well that is *exactly* what I'm doing and if you run the code you will see that the counts are in most cases not the same.

So it seems like there is a real bug here.

Did I miss something?

**Comment by nolanlawson** [comment]
Yeah, sounds like you found a bug. Would be worth trying to figure out if it only occurs with express-pouchdb, or if it is a general Node/LevelDB issue. If it is a general Node/LevelDB issue, then the next step would be to figure out if it's particular to LevelDB or to all adapters, by also testing in a browser. I'll take a look right now.

**Comment by nolanlawson** [comment]
@yaronyg I tried to reproduce your test and could not. Your test fails within your own `writeManyTimesFast` function.

I created a repro to help collaborate on this: https://github.com/nolanlawson/test-express-pouchdb-267. Inside the README are the steps you need to run in order to run your test.

I am using Mac OS X Yosemite and Node 4.0.0.

**Comment by nolanlawson** [comment]
cannot repro

**Comment by sebseb30** [comment]
I have a similar problem but different way...
I have a couple of PouchDB database in sync mode with CouchDB server
And one database, one with attachments, never update doc_count on db.info() other db with same fontction do it... But update_seqence grow up...
After restar the app doc_count is good

**Comment by gerald-dotcom** [comment]
@nolanlawson I'm having similar issue. Are you willing to help me out?
