### ISSUE TITLE
Reconcile with pouchdb-express-router

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/express-pouchdb#271]
After discussing https://github.com/pouchdb/express-pouchdb/issues/268 with @gr2m, we came to the conclusion that this repo has grown too complex/heavyweight for folks to figure out how to meaningfully contribute to it. E.g. he would like to rewrite the auth system since it has a fundamental design flaw (storing credentials in a separate database instead of just checking a hash), but he doesn't know where to start.

I think the best approach is to revive the discussion in https://github.com/pouchdb/express-pouchdb/issues/122 and try to find a way to refactor `express-pouchdb` into two parts: a core `pouchdb-express-router` that just contains the minimum required for PouchDB syncing, and `express-pouchdb`, which contains `pouchdb-express-router` as well as auth, list, show, update, etc.

The last time we had this discussion (#122), @marten-de-vries and I hashed out a solution where "modes" (https://github.com/pouchdb/express-pouchdb/commit/3920710f2ef09b6fbadac65983a9cdc2bd0ba6e3) were used to progressively remove modules (as opposed to progressively adding modules). However, this 1) goes against the whole "small modules" ethos, and 2) doesn't seem very popular with either @gr2m (who is [already working on a separate repo](https://github.com/hoodiehq/hoodie-server-account/tree/node-sessions#wip-node-sessions)) or @daleharvey (who is continuing to work with [pouchdb-express-router](https://github.com/daleharvey/pouchdb-express-router)).

I think it is silly for us to be writing the same code in three different places. So can we please put our heads together and figure out a way to split this repo up?

**Comment by gr2m** [comment]
:pray:

**Comment by marten-de-vries** [comment]
I'd love to split express-pouchdb up, but I don't know how to do so.

The problem is essentially that there are a lot of instances were functionality is added to endpoints in 'full' mode, and it's impossible to just add it in transparently on top without duplicating the code. A few random examples:
- modifying behaviour based on a /_config setting (e.g. specifying the max length of a json request)
- adding validation (read & write)
- adding db_size to /_info

When instead starting with and building on top of @daleharvey's project, you'd encounter the same problem. So, anybody any ideas on how to solve that?

**Comment by nolanlawson** [comment]
Closing since this probably won't happen. Instead we'll move both projections into the PouchDB monorepo and maintain them both, at least in the long term.
