### ISSUE TITLE
How to run Fauxton

### ISSUE THREAD

**Issue by DQvsRA** [pouchdb/express-pouchdb#422]
My setup next:

const LOCAL_POUCH = POUCHDB.defaults(
{
    prefix: './db/data'
});

const EXPRESS_POUCH = require('express-pouchdb')(LOCAL_POUCH,
{
    configPath: "./db/config.json",
    logPath: "./logs/pouchlog.txt",
    mode: 'minimumForPouchDB',
    overrideMode: {
        include: ['routes/fauxton']
    }
});

But i still don't understand how to run Fauxton with express-pouchdb.
Could someone explain it more clearly, please?

**Comment by DQvsRA** [comment]
Solved by implementing code from last comment of this issue
https://github.com/pouchdb/express-pouchdb/issues/290

**Comment by DQvsRA** [comment]
It's strange but after restarting server i have a problem like this:

![screenshot from 2017-01-29 14 12 35](https://cloud.githubusercontent.com/assets/442111/22404244/040e920a-e62d-11e6-93d2-e32b6e6519b9.png)

Can anybody help please?

**Comment by nolanlawson** [comment]
Fauxton has been upgraded, there are now instructions for building pouchdb-server's version of Fauxton from source here: https://github.com/pouchdb/pouchdb-fauxton

**Comment by michael-ts** [comment]
@nolanlawson  This is clear as mud.  Am I supposed to follow the instructions under "How it works"?  I don't think so - that sounds like a description of what pouchdb-fauxton is doing so that I don't have to.   And if it were, I have no idea what #2 would entail, and it would seem highly inappropriate for *me* to do step #4 - I'm not the maintainer of the package!

I don't think the "development" section is referring to me, either.  In any case, I get an error if I even try to run `npm link` in the pouchdb-fauxton directory.

That leaves... exactly no instructions of what I'm supposed to do.  I see pouchdb-fauxton *already* installed in my node_modules directory, so it seems like there is just some missing linkage to get express to serve up the pages.  Specifically, when I go to /db/_utils I get 404s when it tries to get the Fauxton files because express doesn't know how to serve them up.

So...exactly what am I supposed to do to get this to work?  I tried the suggestion of @DQvsRA  - it never even calls the fauxtonIntercept function.  The only difference I can see is that in my code by necessity I am using an express router, not the bare app.

**Comment by michael-ts** [comment]
@nolanlawson  Any clues?  I've been blocked on this for over a month.
